[project]
name = "cve-2025-64446-fortiweb"
version = "0.1.0"
description = "CVE-2025-64446 reproduction lab"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
]
